# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{ pkgs, lib }:

let
  inherit (pkgs.stdenv)
    isDarwin
    isLinux
    isi686
    isx86_64
    isAarch32
    isAarch64
    ;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
merge
  (merge
    (merge
      (merge
        {
          "streetsidesoftware"."code-spell-checker" = vscode-utils.extensionFromVscodeMarketplace {
            name = "code-spell-checker";
            publisher = "streetsidesoftware";
            version = "4.0.38";
            sha256 = "162wcfgi2hd4n9la03cqwp5za6y81xxlxnflfmpg8ila8f381k5y";

          };
          "christian-kohler"."path-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
            name = "path-intellisense";
            publisher = "christian-kohler";
            version = "2.10.0";
            sha256 = "06x9ksl4bghfpxh4n65d1d7dr11spl140p9ch4mc01nrdibgckbc";

          };
          "ritwickdey"."liveserver" = vscode-utils.extensionFromVscodeMarketplace {
            name = "liveserver";
            publisher = "ritwickdey";
            version = "5.7.9";
            sha256 = "0dycc18i1zn20zgh5ymqbi1nmg2an49ndf9r2w6dr5lx8d49hh63";

          };
          "yoavbls"."pretty-ts-errors" = vscode-utils.extensionFromVscodeMarketplace {
            name = "pretty-ts-errors";
            publisher = "yoavbls";
            version = "0.6.1";
            sha256 = "0pjhai8p4zm186hr61fn6z1mhrw639wvkgnsfy6sr093f7bgdx9f";

          };
          "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
            name = "catppuccin-vsc";
            publisher = "catppuccin";
            version = "3.16.1";
            sha256 = "14pb2d21c6hiw43hbmliq061nhrm2bghrklnjkfmwny3rpki0k58";

          };
          "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
            name = "prettier-vscode";
            publisher = "esbenp";
            version = "11.0.0";
            sha256 = "1fcz8f4jgnf24kblf8m8nwgzd5pxs2gmrv235cpdgmqz38kf9n54";

          };
          "mkhl"."direnv" = vscode-utils.extensionFromVscodeMarketplace {
            name = "direnv";
            publisher = "mkhl";
            version = "0.17.0";
            sha256 = "1n2qdd1rspy6ar03yw7g7zy3yjg9j1xb5xa4v2q12b0y6dymrhgn";

          };
          "formulahendry"."auto-rename-tag" = vscode-utils.extensionFromVscodeMarketplace {
            name = "auto-rename-tag";
            publisher = "formulahendry";
            version = "0.1.10";
            sha256 = "0nyilwfs2kbf8v3v9njx1s7ppdp1472yhimiaja0c3v7piwrcymr";

          };
          "christian-kohler"."npm-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
            name = "npm-intellisense";
            publisher = "christian-kohler";
            version = "1.4.5";
            sha256 = "1av0iwym6j5l2a522ikyjkrsyp4q3sws1d7y9brm3gdgghd8aawn";

          };
          "formulahendry"."auto-close-tag" = vscode-utils.extensionFromVscodeMarketplace {
            name = "auto-close-tag";
            publisher = "formulahendry";
            version = "0.5.15";
            sha256 = "0h6nb9paw45v0shzih4486dgin64bsn889cgj9k1hjmvcqs5sm7j";

          };
          "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
            name = "nix-ide";
            publisher = "jnoortheen";
            version = "0.4.12";
            sha256 = "0rdq9wnqfrj8k1g5fcaam5iahzd16bdpi3sa0n2gi0rh02kg55fy";

          };
          "pkief"."material-icon-theme" = vscode-utils.extensionFromVscodeMarketplace {
            name = "material-icon-theme";
            publisher = "pkief";
            version = "5.19.0";
            sha256 = "16ly295r3ibi42dhj24iks7b8mz0blw4mrq6g9v7w3l1lf45y3cf";

          };
          "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
            name = "gitlens";
            publisher = "eamodio";
            version = "2025.2.1304";
            sha256 = "0k0hxqb72vvcxkmxwj8pibl3ba8pvyx48w025am055p19k0mz4kx";

          };
          "ziglang"."vscode-zig" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-zig";
            publisher = "ziglang";
            version = "0.6.4";
            sha256 = "1dkb9kbgr5amfnhvxv3kd71a3wycqsf9hrwh4axbw43sn2383fpq";

          };
          "dsznajder"."es7-react-js-snippets" = vscode-utils.extensionFromVscodeMarketplace {
            name = "es7-react-js-snippets";
            publisher = "dsznajder";
            version = "4.4.3";
            sha256 = "1xyhysvsf718vp2b36y1p02b6hy1y2nvv80chjnqcm3gk387jps0";

          };
          "aaron-bond"."better-comments" = vscode-utils.extensionFromVscodeMarketplace {
            name = "better-comments";
            publisher = "aaron-bond";
            version = "3.0.2";
            sha256 = "15w1ixvp6vn9ng6mmcmv9ch0ngx8m85i1yabxdfn6zx3ypq802c5";

          };
          "alefragnani"."project-manager" = vscode-utils.extensionFromVscodeMarketplace {
            name = "project-manager";
            publisher = "alefragnani";
            version = "12.8.0";
            sha256 = "1gp2dd4xm5a4dmaikcng79mfcb8a24mddsdwpgg4bqshcz4q7n5h";

          };
          "formulahendry"."auto-complete-tag" = vscode-utils.extensionFromVscodeMarketplace {
            name = "auto-complete-tag";
            publisher = "formulahendry";
            version = "0.1.0";
            sha256 = "14xmglw17wlzsil9dpbnn96kvzavfds6xmyf4s9crxydm1swpgsz";

          };
          "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
            name = "even-better-toml";
            publisher = "tamasfe";
            version = "0.21.2";
            sha256 = "0208cms054yj2l8pz9jrv3ydydmb47wr4i0sw8qywpi8yimddf11";

          };
          "bradlc"."vscode-tailwindcss" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-tailwindcss";
            publisher = "bradlc";
            version = "0.14.4";
            sha256 = "1bv1bprq0bnc4iy0ys0853jlchr49zn1x9clb73lx6nscbf5pmn3";

          };
          "nefrob"."vscode-just-syntax" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-just-syntax";
            publisher = "nefrob";
            version = "0.8.0";
            sha256 = "0px83ylzzd18sn92nd2dmq38z9av3qbz8s8wamls8l3230ixzq6f";

          };
          "editorconfig"."editorconfig" = vscode-utils.extensionFromVscodeMarketplace {
            name = "editorconfig";
            publisher = "editorconfig";
            version = "0.17.0";
            sha256 = "0yqw6hvypzpw10m3m967hk5daxp6gyjdaxmbh414n5qmlv8bzmgw";

          };
          "foxundermoon"."shell-format" = vscode-utils.extensionFromVscodeMarketplace {
            name = "shell-format";
            publisher = "foxundermoon";
            version = "7.2.5";
            sha256 = "0a874423xw7z6zjj7gzzl39jahrrqcf2r16zbcvncw23483m3yli";

          };
          "dbaeumer"."vscode-eslint" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-eslint";
            publisher = "dbaeumer";
            version = "3.0.13";
            sha256 = "0yjrylvkw5q9w7kjigndm5m66qn8nranrm0m7qna8ggi0f2nz5cp";

          };
        }
        (
          lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) {
            "ms-vscode"."cpptools" = vscode-utils.extensionFromVscodeMarketplace {
              name = "cpptools";
              publisher = "ms-vscode";
              version = "1.24.0";
              sha256 = "1x8aa5yfhqdr4gb6idmjv5f7b45dbnh9d6qb3gg0k2lsvk2rmd00";
              arch = "linux-x64";

            };
            "supermaven"."supermaven" = vscode-utils.extensionFromVscodeMarketplace {
              name = "supermaven";
              publisher = "supermaven";
              version = "1.1.12";
              sha256 = "1ww6g7jzbhi9jjvfmpic0bkj5hjbr04fl5v4s4100zj4sdsqv2cz";
              arch = "linux-x64";

            };
            "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
              name = "rust-analyzer";
              publisher = "rust-lang";
              version = "0.4.2302";
              sha256 = "1vam7glbi90iqszbw0bwkacr655inpb2hn0aksh3w55c53bfg308";
              arch = "linux-x64";

            };
          }
        )
      )
      (
        lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) {
          "ms-vscode"."cpptools" = vscode-utils.extensionFromVscodeMarketplace {
            name = "cpptools";
            publisher = "ms-vscode";
            version = "1.24.0";
            sha256 = "1bad584ria9gnzjhmsplqd4rfk0a0xfr1xjc1khjix2cg0n59j95";
            arch = "linux-arm64";

          };
          "supermaven"."supermaven" = vscode-utils.extensionFromVscodeMarketplace {
            name = "supermaven";
            publisher = "supermaven";
            version = "1.1.12";
            sha256 = "125a4c4kammvlzi1fvj5hh4ykzyiv7lqh9pk5blcxad5gr0m2l2d";
            arch = "linux-arm64";

          };
          "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
            name = "rust-analyzer";
            publisher = "rust-lang";
            version = "0.4.2302";
            sha256 = "04sqbcjnhd6rgqcb5mq0zmbgi4ss454cf8lsw8riv8wrz9aq16hl";
            arch = "linux-arm64";

          };
        }
      )
    )
    (
      lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) {
        "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "rust-analyzer";
          publisher = "rust-lang";
          version = "0.4.2302";
          sha256 = "1p8wan3yqxzm294nw86jiqamfdj70pb3gbfnlcyndlp7jg3khyli";
          arch = "darwin-x64";

        };
        "supermaven"."supermaven" = vscode-utils.extensionFromVscodeMarketplace {
          name = "supermaven";
          publisher = "supermaven";
          version = "1.1.12";
          sha256 = "03j8mm28l8mjbwrpvknvrq4n2a4a7dizmf01l8115xkkmm1w65kw";
          arch = "darwin-x64";

        };
        "ms-vscode"."cpptools" = vscode-utils.extensionFromVscodeMarketplace {
          name = "cpptools";
          publisher = "ms-vscode";
          version = "1.24.0";
          sha256 = "1yy4izqg3i1wf29snqcalnq50p9l2nq5pbjhqfivd9lzfg945rzm";
          arch = "darwin-x64";

        };
      }
    )
  )
  (
    lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) {
      "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
        name = "rust-analyzer";
        publisher = "rust-lang";
        version = "0.4.2302";
        sha256 = "0l752nrvm4zsniixlblhlyb3rk00cix1ihi6amv4g6lpaskyhn2a";
        arch = "darwin-arm64";

      };
      "ms-vscode"."cpptools" = vscode-utils.extensionFromVscodeMarketplace {
        name = "cpptools";
        publisher = "ms-vscode";
        version = "1.24.0";
        sha256 = "1lik6igghnsvr3m0zlrm674ikmhpgwh9barvdii72mwl9gwfrrfm";
        arch = "darwin-arm64";

      };
      "supermaven"."supermaven" = vscode-utils.extensionFromVscodeMarketplace {
        name = "supermaven";
        publisher = "supermaven";
        version = "1.1.12";
        sha256 = "0lkjhh60ynjysrs79qffjgkpzh5kwyaqlfyhf8yrfm8hrrqg28xn";
        arch = "darwin-arm64";

      };
    }
  )
